---
title: "stats-project"
author: "David Grijalva & Ricco Ferraro"
date: "11/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(car)
library(data.table)
library(mltools)
library(olsrr)
library(scales)
library(caret)
library(dataPreparation)
library(regclass)
# options
#options(scipen = 999)
```



```{r message=FALSE, warning=FALSE}
data_train= read_csv("../Data/train.csv")
data_test = read_csv("../Data/test.csv")
#Convert <chr> to <fctr>
data_train = as.data.frame(unclass(data_train))
data_train$Neighborhood = as.factor(data_train$Neighborhood )
data_test = as.data.frame(unclass(data_test))
data_test$Neighborhood = as.factor(data_test$Neighborhood )
# add new remodel variable
data_train$Remodel =ifelse(data_train$YearBuilt==data_train$YearRemodAdd, 0, 1)
data_test$Remodel =ifelse(data_test$YearBuilt==data_test$YearRemodAdd, 0, 1)
data_train$GrLivArea2 = data_train$GrLivArea^2
data_test$GrLivArea2 = data_test$GrLivArea^2
dim(data_train)
dim(data_test)

```

```{r}
 # In this function we will handle missing values ffor numerical and factor columns 
impute_missing_values_func = function(data){
 
  # create list of  Numerical Columns names
    nums_col = data %>% purrr::discard(~!is.numeric(.)) %>% names
    
    # create list of  factor Columns names
    char_col = data %>% purrr::discard(~!is.character(.)) %>% names
    
    # Create a new dataframe for q2 train data, this is a copy of the original train DF
    treated_data = data
    
    
    # Input NA's in numerical columns with the mediam value per column
    for (i in nums_col){
     treated_data = treated_data %>% mutate_at(vars(UQ(as.name(i))),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
    }
    
    # Create a new factor level called None for each NA in factor columns
    for (i in char_col){
      treated_data[i][is.na(treated_data[i])] = "None"
    }
    
    return(treated_data)
  
}
    
show_missing_values = function(data){
      missing.values <- data %>%
        gather(key = "key", value = "val") %>%
        mutate(is.missing = is.na(val)) %>%
        group_by(key, is.missing) %>%
        summarise(num.missing = n()) %>%
        filter(is.missing==T) %>%
        select(-is.missing) %>%
        arrange(desc(num.missing))
    
    print(missing.values$key)
  
}    
    
    
```

```{r message=FALSE, warning=FALSE}
# Let's handle the missing values
# show missing values on train DF


#show_missing_values(data_train)
#show_missing_values(data_test)
#data_train_q2 = impute_missing_values_func(data_train)
#data_test_q2 = impute_missing_values_func(data_test)

# show missing values on treated train DF - there should be 0
#show_missing_values(data_train_q2)
#show_missing_values(data_test_q2)

```


```{r}

#encoding = build_encoding(data_set = data_train_q2, cols = "auto", verbose = TRUE)
#enconded_data_train_q2 = one_hot_encoder(data_set = data_train_q2, encoding = encoding, drop = TRUE, verbose = F)
#enconded_data_test_q2 = one_hot_encoder(data_set = data_test_q2, encoding = encoding, drop = TRUE, verbose = F)
#print(dim(enconded_data_train_q2))
#print(dim(enconded_data_test_q2))

```





```{r message=FALSE, warning=FALSE}

# Select relevant columns and Neighborhood
train_data_q1 = data_train %>% select(Id, GrLivArea, Neighborhood, SalePrice ) %>% filter(Neighborhood == "NAmes" | Neighborhood ==  "Edwards" | Neighborhood ==  "BrkSide") %>% droplevels()
test_data_q1 = data_test  %>% select(Id, GrLivArea, Neighborhood ) %>% filter(Neighborhood == "NAmes" | Neighborhood ==  "Edwards" | Neighborhood ==  "BrkSide") %>% droplevels()



selected_features_q2 = c("GrLivArea", "Neighborhood", "LotArea", "YrSold", "SaleCondition", "HouseStyle", "KitchenQual", "YearRemodAdd","GarageCars", "PoolArea", "Fireplaces","BsmtFullBath","BsmtHalfBath","FullBath","HalfBath","BedroomAbvGr","Remodel","OverallQual", "GrLivArea2","X1stFlrSF","X2ndFlrSF","PoolArea")

train_data_q2 = data_train %>% select(Id, selected_features_q2,  SalePrice)





# 2.5Fin does not exist in test data so changing it to 1.5Unf
train_data_q2$HouseStyle = as.character(train_data_q2$HouseStyle)
train_data_q2 = train_data_q2 %>%   mutate_at(vars(HouseStyle) ,     ~ifelse(.x=="2.5Fin","1.5Unf",.x  ))
train_data_q2$HouseStyle = as.factor(train_data_q2$HouseStyle)


train_data_q2_process = preProcess(train_data_q2[,2:22], method=c("center", "scale"))
train_data_q2 =  predict(train_data_q2_process, train_data_q2)

test_data_q2 = data_test %>%  select(Id, selected_features_q2)
test_data_q2 =  predict(train_data_q2_process, test_data_q2)





test_data_q2$KitchenQual = as.character(test_data_q2$KitchenQual)
test_data_q2 = test_data_q2 %>%   mutate_at(vars(KitchenQual) ,     ~ifelse(is.na(.x),"Ex",.x  ))
test_data_q2$KitchenQual = as.factor(test_data_q2$KitchenQual)

# Impute = NA in test data
test_data_q2= test_data_q2 %>% mutate_at(vars(GarageCars),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
test_data_q2= test_data_q2 %>% mutate_at(vars(BsmtFullBath),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
test_data_q2= test_data_q2 %>% mutate_at(vars(BsmtHalfBath),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))



summary(test_data_q2)
nrow(test_data_q2)
unique(train_data_q2$HouseStyle)
unique(test_data_q2$HouseStyle)

```

`


Question of interest
Is the square footage of the living area and the neighborhood  related to the house sales price
neighborhood: NAmes, Edwards and BrkSide 
Note:  For living area provide results in increments of 100 sq. ft. 


```{r message=FALSE, warning=FALSE}
# Create scatter plot graphing function

scatter_func = function (data, i){
  title = paste("SalePrice vs GrLivArea by Neighborhood:", i)
  figure = data %>%  filter (Neighborhood==i) %>%  ggplot(aes(x=GrLivArea, y= SalePrice)) + geom_point() + scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +  geom_smooth(formlula="lm") + ggtitle(paste0(title))
return (figure)
}


hist_boxplot = function (data) {
  g1 = data %>% ggplot() + geom_histogram(aes(x=SalePrice), fill="steelblue") + scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) + ggtitle("Histogram of Sale Price")
  g2 = data %>% ggplot() + geom_histogram(aes(x=GrLivArea), fill="steelblue") + scale_x_continuous(labels = function(x) format(x, scientific = FALSE)) + ggtitle("Histogram of Square Footage of the Living Area")
  g3 = data %>% ggplot() + geom_boxplot(aes(x=Neighborhood, y=SalePrice, fill=Neighborhood)) + scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) + ggtitle("Boxplot of Sale Price by Neighborhood") +  
    theme(axis.text.x = element_text(angle = 60, hjust = 1, size = 6 ))
  figure =  ggarrange(g1, g2, g3, ncol=1)
  return(figure)
}

press = function (model) {
  pr = resid(model)/(1 - lm.influence(model)$hat)
  return(sum(pr^2))
}


```






```{r fig.height=5, fig.width=5, message=FALSE, warning=FALSE}
hist_boxplot(train_data_q1)
hist_boxplot(train_data_q2)
```

```{r message=FALSE, warning=FALSE}
for (i in unlist(unique(data_train$Neighborhood)) ) {
  print(scatter_func(data_train, i))
}

```
#	ANALYSIS 1
```{r message=FALSE, warning=FALSE}
one_encode_train_data_q1 =  one_hot(as.data.table(train_data_q1, dropUnusedLevels=TRUE))

#Reference Neighborhood_BrkSide
lm_fit_q1 = lm(SalePrice ~-Id- Neighborhood_BrkSide+ GrLivArea+Neighborhood_Edwards+Neighborhood_NAmes+ Neighborhood_Edwards*GrLivArea+Neighborhood_NAmes*GrLivArea, data = one_encode_train_data_q1)


press(lm_fit_q1)
ols_press(lm_fit_q1)


summary(lm_fit_q1)
confint(lm_fit_q1,  level=0.995)


ols_plot_cooksd_bar(lm_fit_q1)
ols_plot_dffits(lm_fit_q1)
ols_plot_diagnostics(lm_fit_q1)

ols_plot_resid_fit(lm_fit_q1)
ols_plot_resid_pot(lm_fit_q1)
ols_pred_rsq(lm_fit_q1)
plot(lm_fit_q1)
```



#	ANALYSIS 2
```{r message=FALSE, warning=FALSE}
one_encode_train_data_q2 =  one_hot(as.data.table(train_data_q2, dropUnusedLevels=TRUE))
one_encode_train_data_q2
one_encode_test_data_q2 =  one_hot(as.data.table(test_data_q2, dropUnusedLevels=TRUE))


#Refferences: Neighborhood_BrkSide KitchenQual_TA HouseStyle_SLvl SaleCondition_Partial


lm_fit_q2 = lm(SalePrice ~.-SaleCondition_Partial-Id-HouseStyle_SLvl-Neighborhood_BrkSide-KitchenQual_TA+

                  (Neighborhood_Blmngtn+Neighborhood_Blueste+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd )*GrLivArea +

                  (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd)*GrLivArea2 +

                  (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer)*LotArea +

                  (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd ) * BedroomAbvGr


                , data = one_encode_train_data_q2)


# lm_fit_q2 = lm(SalePrice ~.-Id
#               - SaleCondition.Family  
# -SaleType.Oth
# -MiscFeature.TenC 
# -Fence.MnWw 
# -PoolQC.Gd 
# -PavedDrive.P
# -GarageCond.Ex
# -GarageCond.None
# -GarageQual.Po
# -GarageFinish.Fin 
# -GarageType.CarPort
# -FireplaceQu.Po  
# -Functional.Sev 
# -KitchenQual.Fa
# -Electrical.None 
# -CentralAir.N 
# -HeatingQC.Po
# -Heating.Floor
# -BsmtFinType2.GLQ 
# -BsmtFinType1.LwQ  
# -BsmtExposure.None 
# -BsmtCond.Po  
# -BsmtCond.None
# -BsmtQual.Fa 
# -Foundation.Stone 
# -ExterCond.Ex  
# -ExterQual.Fa 
# -MasVnrType.BrkCmn
# -Exterior2nd.CBlock 
# -Exterior1st.CBlock
# -RoofMatl.ClyTile
# -RoofStyle.Shed  
# -HouseStyle.2.5Fin 
# -BldgType.Twnhs
# -Condition2.RRAe 
# -Condition1.RRNe 
# -Neighborhood.Blueste
# -MSZoning.RH
# -Alley.Pave 
# -Utilities.NoSeWa 
# -LotConfig.FR3 
# -LandSlope.Sev
# -Street.Grvl
# , enconded_data_train_q2)

summary(lm_fit_q2)
```


## Model Selection
### Stepwise
```{r message=FALSE, warning=FALSE}
#Stepwise Selection
stepwise_fit = ols_step_both_p(lm_fit_q2, pent =0.05, prem=0.05)
stepwise_fit
```
```{r}
stepwise_fit$predictors
```


```{r}
stepwise_model = stepwise_fit$model
ols_press(stepwise_model)
summary(stepwise_model)
confint(stepwise_model)




```

```{r}
ols_plot_cooksd_bar(stepwise_model)

stepwise_model_outliers = ols_plot_cooksd_bar(stepwise_model, print_plot=F)
stepwise_model_outliers

ols_plot_dffits(stepwise_model)
ols_plot_diagnostics(stepwise_model)

ols_plot_resid_fit(stepwise_model)
ols_plot_resid_pot(stepwise_model)
ols_pred_rsq(stepwise_model)
plot(stepwise_fit)
```

```{r}

stepwise_predictions = c(predict(stepwise_model, newdata = one_encode_test_data_q2))
one_encode_test_data_q2[1117,]

stepwise_submission = data.frame(Id= one_encode_test_data_q2$Id, SalePrice=stepwise_predictions)

#write_csv(stepwise_submission, "../kaggleData/stepwiseSelectionPredictions.csv")

nrow(stepwise_submission)
sum(is.na(stepwise_submission))
stepwise_submission_na <- stepwise_submission %>% filter_all(any_vars(is.na(.))) 
stepwise_submission_na
```
```{r}
step_wise_vif = VIF(stepwise_model)
step_wise_vif
```


```{r message=FALSE, warning=FALSE}
#Forward Selection
fw_fit = ols_step_forward_p(lm_fit_q2, penter=0.05, details = F)
fw_fit


```

```{r}
fw_model = fw_fit$model
ols_press(fw_model)
summary(fw_model)
#confint(fw_model)


```

```{r}
ols_plot_cooksd_bar(fw_model)


fw_model_outliers = ols_plot_cooksd_bar(fw_model, print_plot=F)
fw_model_outliers

ols_plot_dffits(fw_model)
ols_plot_diagnostics(fw_model)

ols_plot_resid_fit(fw_model)
ols_plot_resid_pot(fw_model)
ols_pred_rsq(fw_model)
plot(fw_fit)

```


```{r}

fw_predictions = c(predict(fw_model, newdata = one_encode_test_data_q2))


fw_submission = data.frame(Id= one_encode_test_data_q2$Id, SalePrice=fw_predictions)
fw_submission
#write_csv(fw_submission, "../kaggleData/forward SelectionPredictions.csv")

nrow(fw_submission)
sum(is.na(fw_submission))
fw_submission_na <- fw_submission %>% filter_all(any_vars(is.na(.))) 
fw_submission_na
```
```{r}
fw_vif = VIF(fw_model)
c(fw_vif)

```


```{r message=FALSE, warning=FALSE}

bw_fit = ols_step_backward_p(lm_fit_q2, penter=0.05, details = F)
bw_fit
```



```{r}
bw_model = bw_fit$model
ols_press(bw_model)
formatC(ols_press(bw_model), format = "e", digits = 6)
summary(bw_model)
#confint(bw_model)
```



```{r}
ols_plot_cooksd_bar(bw_model)

bw_model_outliers = ols_plot_cooksd_bar(bw_model, print_plot=F)
bw_model_outliers

ols_plot_dffits(bw_model)
ols_plot_diagnostics(bw_model)

ols_plot_resid_fit(bw_model)
ols_plot_resid_pot(bw_model)
ols_pred_rsq(bw_model)
plot(bw_fit)
```


```{r}

bw_predictions = c(predict(bw_model, newdata = one_encode_test_data_q2))
bw_predictions

bw_submission = data.frame(Id= one_encode_test_data_q2$Id, SalePrice=bw_predictions)
bw_submission
#write_csv(bw_submission, "../kaggleData/backwardsSelectionPredictions.csv")

nrow(bw_submission)
sum(is.na(bw_submission))
bw_submission_na <- bw_submission %>% filter_all(any_vars(is.na(.))) 
bw_submission_na

```
```{r}
bw_vif = VIF(bw_model)
c(bw_vif)

```


```{r}
custom_train_data
train_data_q2
```


```{r}
# outliers list
outliers_forward = c(4, 54,   59,   66,   67,   70,   94,  119,  121,  138,  152,  154,  164,  179,  186,  209,  219,  239,  250,  252,  262,  305,  314,  321,  322,  331,  336,  337,  349,  350,  363,  384,  385,  401,  427,  439,  441,  474,  478,  497,  524,  528,  530,  560,  567,  569,  582,  584,
 586,  589,  592,  598,  608,  622,  633,  636,  641,  643,  656,  662,  665,  682,  686,  689,  692,  703,  713,  725,  745,  770,  775,  779,  799,  804,  811,  813,  823,  826,  841,  876,  878,  886,  898,  899,  926,  940,  962,  971, 1018, 1025, 1032, 1045, 1047, 1049, 1063, 1066,
 1069, 1128, 1143, 1156, 1169, 1170, 1174, 1176, 1182, 1183, 1217, 1268, 1269, 1285, 1299, 1311, 1323, 1325, 1327, 1329, 1360, 1387, 1389, 1397, 1416, 1424, 1441)
#outliers_forward = c(1047,770,1047,1424)

custom_train_data = data_train[!(data_train$Id %in% outliers_forward), ]




selected_features_q2 = c("GrLivArea", "Neighborhood", "LotArea", "YrSold", "SaleCondition", "HouseStyle", "KitchenQual", "YearRemodAdd","GarageCars", "Fireplaces","BsmtFullBath","BsmtHalfBath","FullBath","HalfBath","BedroomAbvGr","Remodel","OverallQual", "GrLivArea2","X1stFlrSF","X2ndFlrSF","PoolArea")



custom_train_data = custom_train_data %>% select(Id, selected_features_q2,  SalePrice)





# 2.5Fin does not exist in test data so changing it to 1.5Unf
custom_train_data$HouseStyle = as.character(custom_train_data$HouseStyle)
custom_train_data = custom_train_data %>%   mutate_at(vars(HouseStyle) ,     ~ifelse(.x=="2.5Fin","1.5Unf",.x  ))

custom_train_data$HouseStyle = as.factor(custom_train_data$HouseStyle)

custom_train_data_process = preProcess(custom_train_data[,2:22], method=c("center", "scale"))
custom_train_data =  predict(custom_train_data_process, custom_train_data)

custom_test_data = data_test %>%  select(Id, selected_features_q2)
custom_test_data =  predict(custom_train_data_process, custom_test_data)





custom_test_data$KitchenQual = as.character(custom_test_data$KitchenQual)
custom_test_data = custom_test_data %>%   mutate_at(vars(KitchenQual) ,     ~ifelse(is.na(.x),"Ex",.x  ))
custom_test_data$KitchenQual = as.factor(custom_test_data$KitchenQual)

# Inpute = NA in test data
custom_test_data= custom_test_data %>% mutate_at(vars(GarageCars),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
custom_test_data= custom_test_data %>% mutate_at(vars(BsmtFullBath),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
custom_test_data= custom_test_data %>% mutate_at(vars(BsmtHalfBath),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))




one_encode_custom_train_data=  one_hot(as.data.table(custom_train_data, dropUnusedLevels=TRUE))

one_encode_custom_test_data =  one_hot(as.data.table(custom_test_data, dropUnusedLevels=TRUE))








#Refferences: Neighborhood_BrkSide KitchenQual_TA HouseStyle_SLvl SaleCondition_Partial


lm_fit_custom = lm(SalePrice ~.-SaleCondition_Partial-Id-HouseStyle_SLvl-Neighborhood_BrkSide-KitchenQual_TA+
                 
                 (Neighborhood_Blmngtn+Neighborhood_Blueste+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd )*GrLivArea +
                 
                 (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd)*GrLivArea2 +
                 
                 (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer)*LotArea + 
                
                 (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_Alloca+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd ) * BedroomAbvGr
               
               
               , data = one_encode_custom_train_data)



summary(lm_fit_custom)
ols_press(lm_fit_custom)

```

```{r}
#custom_train_data

```

```{r message=FALSE, warning=FALSE}

custom_fit = ols_step_forward_p(lm_fit_custom, penter=0.05, details = F)
custom_fit
```

```{r}
custom_model = custom_fit$model
ols_press(custom_model)
formatC(ols_press(custom_model), format = "e", digits = 6)
summary(custom_model)
#confint(custom_model)
```


```{r}
ols_plot_cooksd_bar(custom_model)

custom_model_outliers = ols_plot_cooksd_bar(custom_model, print_plot=F)
custom_model_outliers

ols_plot_dffits(custom_model)
ols_plot_diagnostics(custom_model)

ols_plot_resid_fit(custom_model)
ols_plot_resid_pot(custom_model)
ols_pred_rsq(custom_model)
plot(custom_fit)
```
```{r}
custom_model_outliers$outliers$observation

```

```{r}

custom_predictions = c(predict(custom_model, newdata = one_encode_custom_test_data))
custom_predictions

custom_submission = data.frame(Id= one_encode_custom_test_data$Id, SalePrice=custom_predictions)
custom_submission
#write_csv(custom_submission, "../kaggleData/customSelection3Predictions.csv")
```

```{r}

custom1_vif = VIF(custom_model)
c(custom1_vif)
```


```{r}
one_encode_custom_train_data_model2

```




```{r}
one_encode_custom_train_data_model2 = one_encode_custom_train_data

one_encode_custom_train_data_model2$index = seq.int(nrow(one_encode_custom_train_data_model2))
one_encode_custom_train_data_model2



 custom_model_1_outliers = c( 556)
#
#
#
 one_encode_custom_train_data_model2 = one_encode_custom_train_data_model2[!(one_encode_custom_train_data_model2$index %in% custom_model_1_outliers), ]
 one_encode_custom_train_data_model2
#
#
#get original data again without all the outliers. This way we can scale it using only the values we will utilize, we do this to avoid data leaking
 final_one_encode_custom_train_data_model2 = data_train[(data_train$Id %in% one_encode_custom_train_data_model2$Id), ]
 final_one_encode_custom_train_data_model2
```

```{r}
# do all the data preprossesing again
final_one_encode_custom_train_data_model2 = final_one_encode_custom_train_data_model2 %>% select(Id, selected_features_q2,  SalePrice)


# # 2.5Fin does not exist in test data so changing it to 1.5Unf
final_one_encode_custom_train_data_model2$HouseStyle = as.character(final_one_encode_custom_train_data_model2$HouseStyle)
final_one_encode_custom_train_data_model2 = final_one_encode_custom_train_data_model2 %>%   mutate_at(vars(HouseStyle) ,     ~ifelse(.x=="2.5Fin","1.5Unf",.x  ))

final_one_encode_custom_train_data_model2$HouseStyle = as.factor(final_one_encode_custom_train_data_model2$HouseStyle)

custom2_train_data_process = preProcess(final_one_encode_custom_train_data_model2[,2:22], method=c("center", "scale"))
final_one_encode_custom_train_data_model2 =  predict(custom2_train_data_process, final_one_encode_custom_train_data_model2)

final_custom_test_data = data_test %>%  select(Id, selected_features_q2)
final_custom_test_data =  predict(custom2_train_data_process, final_custom_test_data)


final_custom_test_data$KitchenQual = as.character(final_custom_test_data$KitchenQual)
final_custom_test_data = final_custom_test_data %>%   mutate_at(vars(KitchenQual) ,     ~ifelse(is.na(.x),"Ex",.x  ))
final_custom_test_data$KitchenQual = as.factor(final_custom_test_data$KitchenQual)

#  Impute = NA in test data
final_custom_test_data= final_custom_test_data %>% mutate_at(vars(GarageCars),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
final_custom_test_data= final_custom_test_data %>% mutate_at(vars(BsmtFullBath),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))
final_custom_test_data= final_custom_test_data %>% mutate_at(vars(BsmtHalfBath),~ifelse(is.na(.x), median(.x, na.rm = TRUE), .x))




one_encode_custom_train_data2=  one_hot(as.data.table(final_one_encode_custom_train_data_model2, dropUnusedLevels=TRUE))

one_encode_custom_test_data2 =  one_hot(as.data.table(final_custom_test_data, dropUnusedLevels=TRUE))


# #References: Neighborhood_BrkSide KitchenQual_TA HouseStyle_SLvl SaleCondition_Partial
# # Manual exclusion:
# # take away PoolArea due to 0 variance warning
# #SaleCondition_AdjLand:GrLivArea2           NA         NA      NA       NA
# #SaleCondition_Alloca:GrLivArea2            NA         NA      NA       NA
# #LotArea:SaleCondition_AdjLand              NA         NA      NA       NA
# #LotArea:SaleCondition_Alloca               NA         NA      NA       NA
# #SaleCondition_Alloca:BedroomAbvGr          NA         NA      NA       NA

lm_fit_custom2 = lm(SalePrice ~.-SaleCondition_Partial-Id-HouseStyle_SLvl-Neighborhood_BrkSide-KitchenQual_TA-PoolArea+

                  (Neighborhood_Blmngtn+Neighborhood_Blueste+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd )*GrLivArea +

                  (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_AdjLand+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd)*GrLivArea2 +

                  (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml++SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer)*LotArea +

                  (Neighborhood_Blmngtn+Neighborhood_BrDale+Neighborhood_ClearCr+Neighborhood_CollgCr+Neighborhood_Crawfor+Neighborhood_Edwards+Neighborhood_Gilbert+Neighborhood_IDOTRR+Neighborhood_MeadowV+Neighborhood_Mitchel+Neighborhood_NAmes+Neighborhood_NPkVill+Neighborhood_NridgHt+Neighborhood_NWAmes+Neighborhood_OldTown+Neighborhood_Sawyer+Neighborhood_SawyerW+Neighborhood_Somerst+Neighborhood_StoneBr+Neighborhood_SWISU+Neighborhood_Timber+Neighborhood_Veenker+SaleCondition_Abnorml+SaleCondition_Family+SaleCondition_Normal+HouseStyle_1.5Fin+HouseStyle_1.5Unf+HouseStyle_1Story+HouseStyle_2.5Unf+HouseStyle_2Story+HouseStyle_SFoyer+KitchenQual_Ex+KitchenQual_Fa+KitchenQual_Gd ) * BedroomAbvGr


                , data = one_encode_custom_train_data2)



summary(lm_fit_custom2) 


ols_press(lm_fit_custom2)

```


```{r message=FALSE, warning=FALSE}

custom_fit2 = ols_step_forward_p(lm_fit_custom2, penter=0.05, details = F)
custom_fit2
```

```{r}
custom_model2 = custom_fit2$model
ols_press(custom_model2)
formatC(ols_press(custom_model2), format = "e", digits = 6)
summary(custom_model2)
# confint(custom_model2)
```


```{r}
 ols_plot_cooksd_bar(custom_model2)
# 
custom_model_outliers2 = ols_plot_cooksd_bar(custom_model2, print_plot=F)
custom_model_outliers2
# 
ols_plot_dffits(custom_model2)
ols_plot_diagnostics(custom_model2)
# 
ols_plot_resid_fit(custom_model2)
ols_plot_resid_pot(custom_model2)
ols_pred_rsq(custom_model2)
plot(custom_fit2)
```

```{r}

# custom_model_outliers2$outliers$observation

```

```{r}

custom_predictions2 = c(predict(custom_model2, newdata = one_encode_custom_test_data2))
# 
# 
custom_predictions2 = data.frame(Id= one_encode_custom_test_data2$Id, SalePrice=custom_predictions2)
custom_predictions2
#write_csv(custom_predictions2, "../kaggleData/customSelection4Predictions.csv")
```
```{r}

custom2_vif = VIF(custom_model2)
c(custom2_vif)
```

```{r}
#custom_model2$terms

```


```{r}

#custom_fit3 = ols_step_both_p(lm_fit_custom2, penter=0.05, details = F)
# OverallQual        X1stFlrSF  HouseStyle_2Story  GrLivArea    KitchenQual_Gd:GrLivArea   GrLivArea2:KitchenQual_Gd   



lm_fit_custom3 = lm(SalePrice ~ OverallQual  + GarageCars + 
    BsmtFullBath + KitchenQual_Ex + YearRemodAdd + Neighborhood_OldTown + 
    LotArea + GrLivArea:KitchenQual_Gd + Neighborhood_Crawfor + 
    Neighborhood_NridgHt + SaleCondition_Abnorml + Neighborhood_Somerst + 
    HalfBath + Neighborhood_Edwards + SaleCondition_Normal + 
    SaleCondition_Alloca + BsmtHalfBath + FullBath + Neighborhood_ClearCr + 
    Neighborhood_MeadowV + Neighborhood_SawyerW + Neighborhood_Mitchel + 
    Neighborhood_BrDale + SaleCondition_Family + SaleCondition_AdjLand + 
    Neighborhood_IDOTRR + YrSold + Neighborhood_NPkVill + HouseStyle_SFoyer + 
    Neighborhood_Timber + KitchenQual_Fa + Neighborhood_Sawyer + 
     Neighborhood_Blueste + Fireplaces + Neighborhood_Blmngtn + 
    Neighborhood_CollgCr + Neighborhood_Gilbert + Neighborhood_Veenker + 
    Neighborhood_StoneBr + HouseStyle_1.5Unf + Remodel + Neighborhood_SWISU + 
    HouseStyle_1.5Fin + BedroomAbvGr + HouseStyle_1Story + HouseStyle_2.5Unf + 
     Neighborhood_NWAmes + KitchenQual_Gd +  
    Neighborhood_NAmes + Neighborhood_NAmes:GrLivArea2 + Neighborhood_NoRidge + 
    Neighborhood_OldTown:GrLivArea2  + 
    Neighborhood_NridgHt:LotArea + Neighborhood_NridgHt:BedroomAbvGr + 
    Neighborhood_Somerst:GrLivArea2 + Neighborhood_StoneBr:GrLivArea2 + 
    HouseStyle_1Story:GrLivArea2 + GrLivArea:Neighborhood_Sawyer + 
    Neighborhood_Edwards:GrLivArea2 + LotArea:SaleCondition_Abnorml + 
    LotArea:HouseStyle_1Story + KitchenQual_Ex:BedroomAbvGr + 
    KitchenQual_Gd:BedroomAbvGr + Neighborhood_Somerst:LotArea + 
    Neighborhood_Edwards:LotArea + Neighborhood_Veenker:BedroomAbvGr + 
     Neighborhood_NAmes:BedroomAbvGr + 
    SaleCondition_Family:BedroomAbvGr + Neighborhood_CollgCr:BedroomAbvGr + 
    Neighborhood_StoneBr:LotArea + Neighborhood_Timber:GrLivArea2 + 
    Neighborhood_Timber:BedroomAbvGr
                , data = one_encode_custom_train_data2)
summary(lm_fit_custom3)
formatC(ols_press(lm_fit_custom3), format = "e", digits = 6)
```




```{r}
 ols_plot_cooksd_bar(lm_fit_custom3)
# 
custom_model_outliers3 = ols_plot_cooksd_bar(lm_fit_custom3, print_plot=F)
custom_model_outliers3
# 
ols_plot_dffits(lm_fit_custom3)
#ols_plot_diagnostics(lm_fit_custom3)
# 
ols_plot_resid_fit(lm_fit_custom3)
ols_plot_resid_pot(lm_fit_custom3)
ols_pred_rsq(lm_fit_custom3)
plot(lm_fit_custom3)
```




```{r}

custom_predictions3 = c(predict(lm_fit_custom3, newdata = one_encode_custom_test_data2))
# 
# 
custom_predictions3 = data.frame(Id= one_encode_custom_test_data2$Id, SalePrice=custom_predictions3)
custom_predictions3
write_csv(custom_predictions3, "../kaggleData/customSelection5Predictions.csv")
```
```{r}

custom3_vif = VIF(lm_fit_custom3)
c(custom3_vif)
```